# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: C++
on: [push]
jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "RelWithDebInfo"]
        generator: ["Ninja", "Unix Makefiles"]
        compiler: ["clang", "gcc"]
        container_version: [20230621]

    container: ghcr.io/${{ github.repository }}:${{ matrix.container_version }}-cpp

    steps:
      - name: Checkout
        run: |
          git init project && \
          cd project && \
          git remote add origin ${{ github.server_url }}/${{ github.repository }} && \
          git fetch --depth 1 origin ${{ github.sha }} && \
          git checkout FETCH_HEAD

      - name: Configure
        run: |
          cd project/c++ && \
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=toolchain/${{ matrix.compiler }} \
            -G "${{ matrix.generator }}" \
            -S . \
            -B build

      - name: Formatting
        run: cmake --build project/c++/build --target format

      - name: Build
        run: cmake --build project/c++/build

      - name: Test
        run: ctest --test-dir project/c++/build --output-on-failure
